### ISSUE TITLE
Server Search Syntax Yields 400 Bad Request

### ISSUE THREAD

**Issue by toddmichael** [sous-chefs/ossec#69]
Got tripped up today when my seemingly functional wrapper cookbook failed to converge when I pushed to Chef Server (`12.8`).  Here's the relevant search query from `server.rb`:

``` ruby
search_string = 'ossec:[* TO *]'
search_string << " AND chef_environment:#{node['ossec']['server_env']}" if node['ossec']['server_env']
search_string << " AND NOT role:#{node['ossec']['server_role']} AND NOT fqdn:#{node['fqdn']}"
```

This was working fine for me in my Test Kitchen environment using Chef Zero.  When I run in client/server environment though, I get:

``` ruby
Net::HTTPServerException
------------------------
400 "Bad Request"

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ossec/recipes/server.rb:28:in `from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:292:in `block in include_recipe'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `each'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `include_recipe'
  /var/chef/cache/cookbooks/ossec-strata/recipes/server.rb:10:in `from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ossec/recipes/server.rb:

 21:


 22:  ssh_hosts = []
 23:
 24:  search_string = 'ossec:[* TO *]'
 25:  search_string << " AND chef_environment:#{node['ossec']['server_env']}" if node['ossec']['server_env']
 26:  search_string << " AND NOT role:#{node['ossec']['server_role']} AND NOT fqdn:#{node['fqdn']}"
 27:
 28>> search(:node, search_string) do |n|
 29:    ssh_hosts << n['ipaddress'] if n['keys']
 30:
 31:    execute "#{node['ossec']['agent_manager']} -a --ip #{n['ipaddress']} -n #{n['fqdn'][0..31]}" do
 32:      not_if "grep '#{n['fqdn'][0..31]} #{n['ipaddress']}' #{node['ossec']['dir']}/etc/client.keys"
 33:    end
 34:  end
 35:
 36:  template '/usr/local/bin/dist-ossec-keys.sh' do
 37:    source 'dist-ossec-keys.sh.erb'

Platform:
---------
x86_64-linux

epic fail!
```

I was able to get it working by making the following change:

``` ruby
$ git diff recipes/server.rb
diff --git a/recipes/server.rb b/recipes/server.rb
index d0849dc..dc6cf08 100644
--- a/recipes/server.rb
+++ b/recipes/server.rb
@@ -23,7 +23,7 @@ ssh_hosts = []

 search_string = 'ossec:[* TO *]'
 search_string << " AND chef_environment:#{node['ossec']['server_env']}" if node['ossec']['server_env']
-search_string << " AND NOT role:#{node['ossec']['server_role']} AND NOT fqdn:#{node['fqdn']}"
+search_string << " AND NOT (role:#{node['ossec']['server_role']} OR fqdn:#{node['fqdn']})"

 search(:node, search_string) do |n|
   ssh_hosts << n['ipaddress'] if n['keys']
```

I'll submit a fix.  Let me know if my logic is flawed.

**Comment by netflash** [comment]
LGTM

**Comment by tas50** [comment]
This has been fixed
